% SNR定義
SNRMin=0;
SNRInc=5;
SNRMax=30;

% FECを使っていない場合
coding_rate=1;
% Resultにはループ平均値が入っている → 間違っているので、修正したもので上書きする
R_FM64=[]; % FSS-MIMO(MMSE-64)
R_FM32=[];
R_FM16=[];
R_FM8=[];
R_FM4=[];
R_FM2=[];
% 色は適当につけているので、あとで変更する
semilogy(SNRMin+10*log10(coding_rate):SNRInc:SNRMax+10*log10(coding_rate),R_FM64(1,:)','g*--',...
         SNRMin+10*log10(coding_rate):SNRInc:SNRMax+10*log10(coding_rate),R_FM32(1,:)','bx--',...
         SNRMin+10*log10(coding_rate):SNRInc:SNRMax+10*log10(coding_rate),R_FM16(1,:)','m>--',...
         SNRMin+10*log10(coding_rate):SNRInc:SNRMax+10*log10(coding_rate),R_FM8(1,:)','b>--',...
         SNRMin+10*log10(coding_rate):SNRInc:SNRMax+10*log10(coding_rate),R_FM4(1,:)','r>--',...
         SNRMin+10*log10(coding_rate):SNRInc:SNRMax+10*log10(coding_rate),R_FM2(1,:)','m>--')
%      );
legend('block:1',...
       'block:2',...
       'block:4',...
       'block:8',...
       'block:16',...
       'block:32');
xlabel('Eb/No [dB]');
ylabel('BER');
axis([0,30,10^(-5),10^(0)]);
grid;